### ISSUE TITLE
Improve test suite performance

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/esds-build#38]
## Acceptance Criteria

* As a build tool contributor I don't want the mocha unit tests in the test suite to take a long time to run.

## Solutions

don't test the gulp task calls, extract the gulp test functionality into individual functions and test those. The connection between a gulp task and it calling a function has already been tested by the gulp contributors.

**Comment by nathanacurtis** [comment]
@kevinmpowell Testing suite for what?

**Comment by kevinmpowell** [comment]
@nathanacurtis I've updated the AC. Almost all of the build tooling is unit tested using the mocha testing framework.
