### ISSUE TITLE
Injectable Config Feature

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/esds-build#42]
## Acceptance Criteria

* As a module builder I want the ability to flag parts of my module's config so that they're auto-merged into any modules that consume my module.

**Comment by nathanacurtis** [comment]
@kevinmpowell Can you add a sensitizing example? I don't understand the value of this task.

**Comment by kevinmpowell** [comment]
The immediate need for this was in regard to nunjucks filters and that has been resolved via #41. Closing this issue since I can't think of any other reasons to do this at this time.
